In [7]:
import random
import string


# adjective list
adjectives = ["happy", "sad", "angry", "excited", "bored"]
# noun list
nouns = ["dog", "cat", "mouse", "elephant", "tiger"]

def generate_password():
    adjective = random.choice(adjectives)
    noun = random.choice(nouns)
    char = random.choice(string.punctuation)
    number = random.randrange(0, 100)
    return adjective + noun + str(number) + char

def is_satisfied():
    
    while True:
        response = input("Are you satisfied with this password? (yes/no): ").lower()
        if response in ['yes', 'no']:
            return response == 'yes'
        else:
            print("Please enter 'yes' or 'no'.")

def main():
    while True:
        password = generate_password()
        print(f"Generated password: {password}")
        
        if is_satisfied():
            print("Password saved!")
            break
        else:
            print("Generating a new password...")

if __name__ == "__main__":
    main()




Generated password: boredtiger25`
Generating a new password...
Generated password: excitedcat98:
Generating a new password...
Generated password: angrytiger93=
Generating a new password...
Generated password: happycat63[
Generating a new password...
Generated password: sadtiger40^
Generating a new password...
Generated password: boredtiger24[
Generating a new password...
Generated password: happycat94'
Password saved!


In [8]:
#Numpy
import numpy as np

numpy is a python library stand for numerical python. It contains a collection of tools and techniques to solve on a computer mathematical models of problems


In [10]:

print(np.__version__)

1.26.4


In [11]:
# 1-D array
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [14]:
# 2-D array
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(type(b))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [17]:
# 3-D array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(c)
print(type(c))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
<class 'numpy.ndarray'>
