In [7]:
import random
import string


# adjective list
adjectives = ["happy", "sad", "angry", "excited", "bored"]
# noun list
nouns = ["dog", "cat", "mouse", "elephant", "tiger"]

def generate_password():
    adjective = random.choice(adjectives)
    noun = random.choice(nouns)
    char = random.choice(string.punctuation)
    number = random.randrange(0, 100)
    return adjective + noun + str(number) + char

def is_satisfied():
    
    while True:
        response = input("Are you satisfied with this password? (yes/no): ").lower()
        if response in ['yes', 'no']:
            return response == 'yes'
        else:
            print("Please enter 'yes' or 'no'.")

def main():
    while True:
        password = generate_password()
        print(f"Generated password: {password}")
        
        if is_satisfied():
            print("Password saved!")
            break
        else:
            print("Generating a new password...")

if __name__ == "__main__":
    main()




Generated password: boredtiger25`
Generating a new password...
Generated password: excitedcat98:
Generating a new password...
Generated password: angrytiger93=
Generating a new password...
Generated password: happycat63[
Generating a new password...
Generated password: sadtiger40^
Generating a new password...
Generated password: boredtiger24[
Generating a new password...
Generated password: happycat94'
Password saved!


In [3]:
#Numpy
import numpy as np

numpy is a python library stand for numerical python. It contains a collection of tools and techniques to solve on a computer mathematical models of problems


In [10]:

print(np.__version__)

1.26.4


In [4]:
# 1-D array
a = np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
# 2-D array
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(type(b))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [6]:
# 3-D array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(c)
print(type(c))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
<class 'numpy.ndarray'>


In [7]:
#dimmesion of array
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


shape:- It returns the shape of array in tuple , it can also be used to resize the array


In [8]:
print(a.shape)
print(b.shape)
print(c.shape)

(4,)
(2, 4)
(3, 2, 2)


Length : it return  length of array. for n-dimmesional it returns size of the first dimension

In [9]:
print(len(a))
print(len(b))
print(len(c))

4
2
3


dtype :- it return the datatype of array


In [13]:
# d = np.array([1,2,3,4],dtype='float')
d = np.array([1,2,3,4],dtype='complex')
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)
print(d)

int32
int32
int32
complex128
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


size:- it return the total no of elements inside the array

In [14]:
print(a.size)
print(b.size)
print(c.size)

4
8
12


itemsize:-It returns the each element of array in byte size

In [15]:
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

4
4
4


why we use numpy in the palce of list?

In [16]:
%timeit cube = [i**3 for i in range(100)]

14.6 µs ± 334 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [18]:
num = np.arange(100)
%timeit num**3

3.52 µs ± 84.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
import sys
cube = [i**3 for i in range(100)]
print ("Memory space in list",sys.getsizeof(cube)*len(cube))

Memory space in list 92000


In [20]:
num = np.arange(100)
cube = num**3
print("Memory space in list",num.size*cube.itemsize)

400


Array creation ones and zeroes
1. numpy.empty:- return a new array of given shape without intializing it

In [23]:
emp = np.empty((2,2))
print(emp)

[[0. 0.]
 [0. 0.]]


numpyzeroes:- returns a new array of given shapes and type filled with zeroes

In [ ]:
z = np.Zeroes(shape=(5,9))
print(z)